spring:
  profiles:
    group:
      local: "localdb,common"
      server: "serverdb,common"
      devserver: "devserverdb,common"
    active: local
logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  sql:
    init:
      encoding: UTF-8
      continue-on-error: true
      mode: always

---

spring:
  config:
    import: classpath:/localkey.yml
    activate:
      on-profile: localdb
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3306/lolduo
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
slack:
  token: ${localkey.slackapi.token}
riot:
  key: ${localkey.riotapi.key}
server:
  port: '8080'

---

spring:
  config:
    activate:
      on-profile: serverdb
  datasource:
    username: root
    url: jdbc:mariadb://${rds.mariadb.endpoint}:3306/lolduo
    password: ${rds.mariadb.password}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
slack:
  token: ${slackapi.token}
riot:
  key: ${riotapi.key}
server:
  port: '80'

---

spring:
  config:
    activate:
      on-profile: devserverdb
  datasource:
    username: root
    url: jdbc:mariadb://${rds.mariadb.endpoint}:3306/lolduo
    password: ${rds.mariadb.password}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
slack:
  token: ${slackapi.token}
riot:
  key: ${riotapi.key}
server:
  port: '80'